### ISSUE TITLE
Clear skies triggers when you destroy your own light aircraft

### ISSUE THREAD

**Issue by bobmitch** [bobmitch/ps2announcer#13]
![image](https://user-images.githubusercontent.com/23583515/94225165-4d2b1100-fec2-11ea-91dc-aad51f1f9e71.png)

**Comment by bobmitch** [comment]
![image](https://user-images.githubusercontent.com/23583515/94225324-a4c97c80-fec2-11ea-8cc4-0535b43a29cf.png)

**Comment by HeyMyian** [comment]
It's technically correct.

**Comment by bobmitch** [comment]
Closing despite protestations. https://github.com/bobmitch/ps2announcer/commit/1667d4e0ed438a624fb8bebcc3a7740e6eacfa6a
