### ISSUE TITLE
Classes do not seem to be right sometimes

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#14]
The third item in this list was a revive on an Infiltrator. The last item on this list was a MAX (killed me with Blueshift).

![2020-09-25___10-03-35](https://user-images.githubusercontent.com/60368695/94242525-74133280-ff16-11ea-9dc3-8de98ca3b27b.jpg)

**Comment by bobmitch** [comment]
I'm an idiot. When we first encounter another player, I cache the player details for re-use later (don't want to do another api call). I think I'm stupidly using their 'loadout' at the time of initial encountering to then display their class subsequently.
What I need to do is pass the current event to the character display function and use the _current event_ character loadout id to lookup the class.

**Comment by bobmitch** [comment]
Fix in place for this, leaving open for testing.

**Comment by bobmitch** [comment]
This may still be an issue for 4th faction characters - but seems to be ok for regular factions.
