### ISSUE TITLE
Convenience: Don't enable auto paste to clipboard when importing/exporting

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#16]
Perhaps bind it to a button on the popup instead.

**Comment by bobmitch** [comment]
It doesn't auto paste - it auto selects all the text and _copies_.

I can still do this with just a button if you think it's better UX - it's not my area of expertise. :)

**Comment by HeyMyian** [comment]
Yes please - I'm one of these people who click on every option and I didn't even mean to export/import anything - I was just trying to see what this option can do. Having my clipboard overridden without my explicit permission is minorly inconvenient (I've had my audio file URL in there before for testing purposes).

A button next to "Apply Config" that reads "Copy Config to Clipboard" or something like that would be more convenient.

**Comment by bobmitch** [comment]
This work?

![image](https://user-images.githubusercontent.com/23583515/94294779-54880400-ff2e-11ea-98e3-362220f955e7.png)

**Comment by HeyMyian** [comment]
Superb. Thank you 🙂
