### ISSUE TITLE
Custom sound files not playing

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#17]
Error in the console:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxxxx.xxxxxxxx.com/xxxxx/icanseewhy.mp3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

However, the dropbox example link you provided: `https://dl.dropbox.com/s/l8ko7l9c7rxuh7m/payback%27s-a-bitch-ain%27t-it.mp3` works.

**Comment by HeyMyian** [comment]
I should have researched this first, because this is actually fixed on the webserver where the custom file is at.

.htaccess:
`Header set Access-Control-Allow-Origin "https://bobmitch.com"`

I tend to believe it is safe to enable it like this, but I'm no expert.

**Comment by bobmitch** [comment]
It's safer than using a wildcard in place of the domain which a lot of people do after googling. 

I'm not going to be serving up any markup/code that uses your urls anyway, all your stuff is from localstorage, so I can't pass your files off as my own. ;)

**Comment by HeyMyian** [comment]
Do you think there should be a hint at this issue on the website? Depending on how many people will use their own webserver for custom audio files instead of services like Dropbox, and depending on whether or not webservers are usually configured to allow CORS (I've got no clue?), more people might run into this.

I mean I guess I've fixed it for myself so I'm good.

**Comment by bobmitch** [comment]
Can't hurt to put a note in. 

Added this:

![image](https://user-images.githubusercontent.com/23583515/94295517-59998300-ff2f-11ea-924f-7c575f6fb487.png)
