### ISSUE TITLE
navbar-brand "Planetside Announcer" links to bulma.io

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#19]

**Comment by bobmitch** [comment]
Tricky fix applied here: https://github.com/bobmitch/ps2announcer/commit/4633f40103486812454ae489ffac88abab1cd033

**Comment by HeyMyian** [comment]
Line below that one is a severe bug as well. Literally unplayable

**Comment by bobmitch** [comment]
Can you believe I do this for a living....
