### ISSUE TITLE
OBS Streaming View

### ISSUE THREAD

**Issue by bobmitch** [bobmitch/ps2announcer#25]
Hey @HeyMyian - I think this is more viable than we managed during the live-stream-live-test. :)

I installed and played around with OBS - and as long as you don't click the 'refresh cache' of the page:

![image](https://user-images.githubusercontent.com/23583515/94374492-96ee4400-00da-11eb-89a6-e6d3cd9c8f51.png)

... all your localStorage data is retained. So you can just use https://bobmitch.com/ps2 as normal in OBS, use interact, and set up players, import sounds from your desktop browser, and you're good to go. 

All I need to do (all... lol) is make a new button that switches between normal background desktop view, and the OBS view. I can maybe add a URL parameter to start in OBS view, maybe with browser sniffing server-side, but to start with you'll have to interact, click OBS view, and that's it. At least, that's the plan.

**Comment by HeyMyian** [comment]
How... where... what? Where is that information (soundpack and tracked players) stored for it to work like that?

**Comment by bobmitch** [comment]
OBS uses CEF - Chromium Embedded Framework - essentially the chrome rendering engine in it's plugin. So it's just using it's own localstorage container - it's really just another Chrome browser.

More info [here](https://github.com/obsproject/obs-browser/blob/master/README.md) - I can sniff for js variables to detect if the site is loaded by OBS and start in obs view by default, and maybe listen for a keypress in interactive mode (space maybe?) if you want to switch to regular mode to update config. This is pretty neat!

**Comment by bobmitch** [comment]
Current live version will now detect OBS, and will employ a stylesheet to show just the stat pills at the top and any incoming events, pretty much like what we had on your test. Splash screen is also removed - hoping audio still works without the 'click'/browser interaction, it not interaction will be required to make it work.

Switch to desktop mode by pressing 'space' in interactive mode in OBS.

Switch back to OBS mode using the new option in the "More" menu:

![image](https://user-images.githubusercontent.com/23583515/94377497-41249680-00f0-11eb-9b7a-e0b5cfe017cd.png)

I await the next feature request along the lines of 'images or animations when something triggered...' :D

**Comment by bobmitch** [comment]
Went ahead and added an images feature. You can click on the image on any audio trigger here:

![image](https://user-images.githubusercontent.com/23583515/94471630-79cb7b00-0197-11eb-8b3e-6a28770b80d0.png)

Paste in an image url (imgur works well, or your own hosted). 

These will then be displayed to the right hand side of the screen and moved off after a few seconds when those triggers are... triggered:

![image](https://user-images.githubusercontent.com/23583515/94471922-f52d2c80-0197-11eb-8d61-e8b003abd052.png)

Could possibly add different animations to choose from or whatnot, but this core functionality would need to be tested first.

**Comment by HeyMyian** [comment]
*Can we please have images or animations for the triggers?*

What I found, what would make this whole interaction way easier, is that the OBS browser source can actually be interacted by `Right Click` > `Interact`.

What works:

- Space bar to switch back to website view
- Adding characters
- Adjusting glogal volume
- Adding custom sounds (with CTRL+V, because it's a JS prompt, not a Bulma modal) [2020-09-28___21-00-33](https://user-images.githubusercontent.com/60368695/94474299-bc0faf00-01cd-11eb-9621-336760c4668f.jpg)

What does not work:

- Importing custom soundpack (because it's a Bulma modal and OBS will not accept neither context menu nor hotkeys CTRL+C / CTRL+V (presumably because hotkeys are disabled while OBS is in the foreground). Default text in the textarea is `null` for some reason. [2020-09-28___20-54-57](https://user-images.githubusercontent.com/60368695/94474308-bf0a9f80-01cd-11eb-8f6a-5e18702c658d.jpg)

I don't have much time to test further this week, not even *live* on *stream*, but I'm still on it.

**Comment by bobmitch** [comment]
I'm sure your viewers would appreciate nothing more than the constant alt-tabbing into obs to make changes. ;) Appreciate your time on this so far - I've already spent far too much on this vs real work, but it's just way more interesting than client stuff. 

That's a nice find re: copy/paste - there some [recent activity](https://github.com/obsproject/obs-browser/issues/238) surrounding this in the OBS github. I'll replace the bulma modal in 'OBS' mode with a regular js prompt for importing and do some testing myself. Exporting might work ok too with a regular js alert, and I'll test that too.

**Comment by bobmitch** [comment]
OBS config import/export dialog now shows this:

![image](https://user-images.githubusercontent.com/23583515/94483318-acca3a80-01a8-11eb-813c-9e5df40ba6ff.png)

Allows pasting of config string - will apply and close the dialogue if the config is good. 

Desktop version works as before.

**Comment by bobmitch** [comment]
Made a notification system, and it's now used in OBS view for triggers. They are shown top right, and stacked as needed before disappearing:

![image](https://user-images.githubusercontent.com/23583515/94699347-39d7d580-0308-11eb-9d18-cc9ff7f0d19b.png)

Triggers with no custom image are shown are text notifications with trigger title/description:

![image](https://user-images.githubusercontent.com/23583515/94699516-6390fc80-0308-11eb-9e91-97f655d0f591.png)

Triggers can easily be extended later to include custom animations (not showing images in the notification queue).
