### ISSUE TITLE
Implement copy/paste config from non 'owned' urls.

### ISSUE THREAD

**Issue by bobmitch** [bobmitch/ps2announcer#29]
Use new temp localstorage variable

**Comment by bobmitch** [comment]
Copy Sound Pack - button will now appear in Trigger Management screen of any 'claimed' URL. 
Paste Sound Pack - button will now appear in Trigger Management screen of any 'claimed' AND 'authorized' (unlocked) URL.

![image](https://user-images.githubusercontent.com/23583515/95141572-950e2b80-073f-11eb-9909-7bfa514b19fb.png)

@heymyian can you test - works for me, but you are GREAT at finding problems. :)

**Comment by HeyMyian** [comment]
- Upon first claiming a new URL, in the "Manage Triggers" modal there is only one button: "Copy Soundpack". Upon reloading the page and re-entering the passcode in the modal, all three buttons appear, as they should.

- Upon entering a custom audio (issue appears to be unrelated to claiming custom URLs), a JS alert: `No matching achievement found` and custom audio file was not added.

- Upon first pasting a soundpack, none of the "audio preview" buttons are functional (an error appears in the console).

**Comment by bobmitch** [comment]
> * Upon first claiming a new URL, in the "Manage Triggers" modal there is only one button: "Copy Soundpack". Upon reloading the page and re-entering the passcode in the modal, all three buttons appear, as they should.
> * Upon entering a custom audio (issue appears to be unrelated to claiming custom URLs), a JS alert: `No matching achievement found` and custom audio file was not added.
> * Upon first pasting a soundpack, none of the "audio preview" buttons are functional (an error appears in the console).

I _think_ I got 'em all.
