### ISSUE TITLE
Player list multiline needs margin-bottom

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#37]
When one enters enough player names so the tags flow over to a second line, they stick to each other vertically without gap. It's weird because as far as I can see, you used the correct Bulma syntax thingies, but a manual `margin-bottom` somewhere will fix this anyway.

**Comment by bobmitch** [comment]
It's a Bulma potential bug - when I undo this style definition:

![image](https://user-images.githubusercontent.com/23583515/95125585-2e7b1480-0723-11eb-9e03-028a2933c7c3.png)

...it looks better. I'm not even sure what this is supposed to be doing in a flex-wrap flex-box - it seems like something that would be done for a vertical stack to maintain a correct bottom spacing, but not something that wraps horizontally.
