### ISSUE TITLE
Visual: Cards need horizontal margin in smaller browser widths

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#42]
Or a re-organization.

![2020-10-12___10-17-35](https://user-images.githubusercontent.com/60368695/95722414-2f0c3180-0c74-11eb-93e0-bbac649ec9a6.jpg)

**Comment by bobmitch** [comment]
CSS specificity bug with breakpoints fixed. 

Better? Or need rethink?

![image](https://user-images.githubusercontent.com/23583515/95748975-d7b49400-0c68-11eb-9751-df2bda4ba1a9.png)

**Comment by bobmitch** [comment]
Ignore previous comment - issue is with authorized view. Fixing...

**Comment by bobmitch** [comment]
![image](https://user-images.githubusercontent.com/23583515/95749660-eb142f00-0c69-11eb-9b03-085fc5fef2c3.png)

better? or still need ux rethink?

**Comment by HeyMyian** [comment]
Yep that woorks 🙂
