### ISSUE TITLE
Visual (low priority): Buttons in "Manage Triggers" vanish on small screen widths

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#46]
It looks like this:

![2020-10-15___17-04-35](https://user-images.githubusercontent.com/60368695/96148964-11a3c580-0f09-11eb-93fe-0159ae8aee3d.jpg)

The buttons overflow and the `x` is completely lost in the eastern nether. On even smaller widths, the right-most button also vanishes. This is a non-issue because who tf browses the interweb at 2px width, but I reported it anyway.

**Comment by bobmitch** [comment]
Fixed for _reasonable_ screen sizes. :)
