### ISSUE TITLE
Timestamps: minute mark missing leading zero

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#57]
Possibly others as well, but this is where I saw it:
13:3:35

**Comment by bobmitch** [comment]
Fixed in https://github.com/bobmitch/ps2announcer/commit/7ce2cd12a7b438f750726ef92486314a9503f592

![image](https://user-images.githubusercontent.com/23583515/97011278-75834b00-1514-11eb-966a-bdf170f76822.png)
